Frontend 38
Flo-CI/front-end pull request #66
Opened 2023-12-01 03:45 UTC by LevOzay

## Pull Request

### Description

Connected NewClaimScreen to the backend

### Related Issues

Resolves frontend-38

Resolves #

### Changes Made

1-) Removed initial file upload button to simplify MVP.
2-) Used a POST method to send the selected claim type to the backend

### Screenshots (if applicable)

![image](https://github.com/Flo-CI/front-end/assets/116689587/7da47f99-5ccc-4058-803e-a81a102f9dac)

### Checklist

- [X] I have tested the changes locally.
- [X] My code follows the project's coding style.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generate no new warnings or errors.
- [ ] I have added tests that prove my fix is effective or that my feature works.

### Additional Notes (if any)

This screen also uses a static link for the backend, it will be changed when do LoginScreen is connected to the backend and we have a dynamic fetch link for each separate policy number/username.

2023-12-01 17:34 UTC, geraldyywang approved these changes
# Code Review
## Coding style
Good coding style and conventions! Just a slight suggestion for the passing props though, highlighted in my file comments.

## Correctness (checkout the branch and try running the code)
The feature works! Very cool. 

## Documentation
The documentation for the proposed changes are for the most part pretty clear. Great job! See file comments for detailed suggestions.

## Clarity of pull request
This pull request's commit history and description outline the change made well. Good job!

2023-12-01 17:34 UTC, geraldyywang commented on src/components/ClaimFilesButton.js
Please deconstruct props and specify the function you're passing in so that it is more clear to the reader!

2023-12-01 17:34 UTC, geraldyywang commented on src/screens/ClaimDashboardScreen.js
Looks good!

2023-12-01 17:34 UTC, geraldyywang commented on src/screens/NewClaimScreen.js
Maybe can document what result we are expecting from fetch call? Also, comment out console.log debug statements/remove them, we can always add them back to debug. Otherwise, looks good!

2023-12-01 17:37 UTC, geraldyywang requested changes
Accidentally re-requested myself for review. Please fix some of the small changes I noted to improve documentation. Functionality is great though!

2023-12-03 03:02 UTC, geraldyywang approved these changes
Looks good, the documentation is now clear. Good job!

2023-12-03 04:18 UTC, Anshiboy commented
### Pull Request Review Summary
**Coding Style**
The coding style and conventions are well-maintained—great work on adhering to best practices.

**Correctness**
Thorough testing locally confirms that the requests function properly. Creating claims and navigating back to the dashboard shows the expected behavior of the claim being visible. Well done on ensuring functionality.

**Documentation**
The changes made are self-explanatory, requiring no additional comprehensive documentation. The modifications are clear and easily understandable.

**Clarity of Pull Request**
The commit history and description in this pull request excellently outline the changes made. The clarity in outlining the modifications is commendable. Great job!

2023-12-03 04:19 UTC, merged