Testing front end
Flo-CI/front-end pull request #70
Opened 2023-12-04 02:48 UTC by Anshiboy

## Pull Request

### Description

The test files for every single screen and component used in the front-end

### Changes Made

Created individual test files for all screens, and components while intrinsically covering dark mode and store. Do not know what to do with app.test.js, but can be deleted later if not needed. Overall 100% coverage for all components, but only 65% coverage for screens as there were a few hiccups with the connection with backend. Also Document viewer has not been tested yet as a PR to implement it into FilesScreen will be made very shortly.

### Screenshots (if applicable)

<img width="716" alt="image" src="https://github.com/Flo-CI/front-end/assets/87465536/12e97dc2-4ed0-467c-a808-7ce302a71f88">

Coverage for all ^

<img width="705" alt="image" src="https://github.com/Flo-CI/front-end/assets/87465536/7324345c-d95a-42a6-ad62-6c5ecfae6a82">

Tests passing ^ (the one suite that fails is App.js as there is no tests that can be performed for it yet)
### Checklist

- [ ] I have tested the changes locally.
- [ ] My code follows the project's coding style.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings or errors.
- [ ] I have added tests that prove my fix is effective or that my feature works.

### Additional Notes (if any)

2023-12-05 21:28 UTC, GregoryGismondi commented on package.json
Changes look good, no issues or changes with other packages

2023-12-05 21:29 UTC, GregoryGismondi commented on src/App.test.js
File does not have any references so it's deletion is safe

2023-12-05 21:35 UTC, GregoryGismondi approved these changes
# Code Review
## Coding style
Proper coding style and conventions were followed

## Correctness (check the branch and try running the code)
All tests ran and returned a success except App.test.js. However, there are no tests inside to be run which is why the program fails. We can delete src/\_\_test\_\_/App.test.js in a future commit. Below is a screenshot of me running the test locally:

![image](https://github.com/Flo-CI/front-end/assets/37008661/e47623b6-9876-4b3c-8098-74a763b2c339)

Changes to the package.json does not affect other parts of the program. 

The deletion of App.test.js in src folder is safe as it has no references and it was not completed

Update: src/\_\_test\_\_/App.test.js has been removed with no issues. Below are the tests ran again (now without src/\_\_test\_\_/App.test.js): 

![image](https://github.com/Flo-CI/front-end/assets/37008661/9bcde0f8-0422-47da-a3c1-a987253e3dbc)

## Documentation
Documentation for changes and the result of test cases are shown properly with a screenshot

## Clarity of pull request
All commits of the pull request are shown and all code is commented. Nice job overall!

2023-12-05 21:47 UTC, GregoryGismondi commented
Updated approval comment to fit updated commit

2023-12-05 22:05 UTC, sarvaSanjay requested changes
Keep this on hold till further changes are merged. MVP is priority and I don't want the team working on that to have merge conflicts/ other issues

2023-12-05 22:11 UTC, GregoryGismondi commented
> Keep this on hold till further changes are merged. MVP is priority and I don't want the team working on that to have merge conflicts/ other issues

Sounds good! Will re-review any changes that need to be made once MVP is complete

2023-12-07 05:13 UTC, Anshiboy commented
> Keep this on hold till further changes are merged. MVP is priority and I don't want the team working on that to have merge conflicts/ other issues

fixed

2023-12-07 05:15 UTC, sarvaSanjay approved these changes
As MVP is complete, we can merge. Good job connecting all changes

2023-12-07 05:15 UTC, merged